// Copyright(C) 2022 Baidu Inc. All Rights Reserved.
// Code Generated By 'gdp' At 2022-06-22, You Can EDIT.
// App Using GDP Framework: http://gdp.baidu-int.com/ .

package bootstrap

import (
	"api-gateway/library/resource"
	"api-gateway/library/types"
	"errors"
	"os"
	"path/filepath"

	"github.com/BurntSushi/toml"
)

// MustLoadAppConfig 加载 app.toml ,若失败，会 panic
func MustLoadAppConfig(ConfigPath string) {
	// 配置文件load
	err := parserAppConfig(ConfigPath + "app.toml")
	if err != nil {
		panic(err.Error())
	}
}

// checkAppConfig 检查配置是否正确
func checkAppConfig(c *types.Config) error {
	if c.AppName == "" {
		return errors.New("config.AppName is empty")
	}
	if c.RunMode == "" {
		return errors.New("config.RunMode is empty")
	}
	// 自定义
	return nil
}

// parserAppConfig 解析应用配置
func parserAppConfig(filePath string) error {
	confPath, err := filepath.Abs(filePath)
	if err != nil {
		return err
	}

	_, err = toml.DecodeFile(confPath, &resource.Config)
	if err != nil {
		return err
	}
	if err := checkAppConfig(resource.Config); err != nil {
		return err
	}
	// 解析并设置全局应用环境信息
	rootDir := filepath.Dir(filepath.Dir(confPath))
	// 先将程序进程切换到应该的根目录下，这样程序内部可以正常使用相对路径
	if err = os.Chdir(rootDir); err != nil {
		return err
	}

	return nil
}
