// Copyright(C) 2022 Baidu Inc. All Rights Reserved.
// Code Generated By 'gdp' At 2022-06-22, You Can EDIT.
// App Using GDP Framework: http://gdp.baidu-int.com/ .

package bootstrap

import (
	"api-gateway/httpserver"
	"context"
	"net/http"
)

// StartServers 启动服务
func StartServers(ctx context.Context) *http.Server {
	// http server
	return httpserver.NewServer(ctx)
}
