// Copyright(C) 2022 Baidu Inc. All Rights Reserved.
// Code Generated By 'gdp' At 2022-06-22, You Can EDIT.
// App Using GDP Framework: http://gdp.baidu-int.com/ .

package httpserver

import (
	"api-gateway/httpserver/middleware"

	"api-gateway/httpserver/controller/common"

	"github.com/gin-gonic/gin"
)

// httpRouter 获取web路由
//
// HTTP Server 和 Router 的文档：
// http://gdp.baidu-int.com/gdp2/docs/examples/server/20_http_server/
func httpRouter() *gin.Engine {
	router := gin.New()

	// 日志中间件
	router.Use(middleware.NewAccessLogMiddleware())

	// defer recover 错误处理
	router.Use(middleware.NewDeferErrorMiddleware())

	// 跨域支持
	router.Use(middleware.NewCorsMiddleware())

	// register(router)
	routerRegister(router)

	return router
}

func routerRegister(r *gin.Engine) {

	apiGroup := r.Group("/api")
	apiGroup.Use()
	{
		apiCommonGroup := apiGroup.Group("/common")
		apiCommonGroup.GET("/probe", common.Probe)
	}
}
